= RUST

This is my Rust learning

== First program

see: https://doc.rust-lang.org/book/ch01-02-hello-world.html[Hello, World!]

ifdef::env-github[]
Write your program in a `link:tutorial/helloworld/main.rs[main.rs]` file.
endif::[]

ifndef::env-github[]
.File `main.rs`
----
include::tutorial/helloworld/main.rs[]
----
endif::env-github[]

.Launch docker
----
docker run -it -v $(pwd):/project -w /project/tutorial/helloworld rust /bin/bash
----

.Build and run program
----
rustc main.rs && ./main
----

You should see `Hello world!` in console.

== Using cargo

see: link:https://doc.rust-lang.org/book/ch01-03-hello-cargo.html[Hello, Cargo!]

In a folder, init a project with `cargo new [PROJECT_NAME]`.

It will create a folder that contains a `link:tutorial/hellocargo/Cargo.toml[Cargo.toml]` file and a `src` folder.

ifndef::env-github[]
[%collapsible]
.Cargo.toml
====
----
include::tutorial/hellocargo/Cargo.toml[]
----
====
endif::[]

.Build and run program
cargo build && target/debug/hello_cargo 

The program name `hello_cargo` comes from the `Cargo.toml` file.


== First test

see: https://doc.rust-lang.org/book/ch11-01-writing-tests.html[How to Write Tests]

Create a project with `Cargo`. +
Create a file `link:tutorial/tests/src/lib.rs[lib.rs]`.

ifndef::env-github[]
[%collapsible]
.lib.rs
====
----
include::tutorial/tests/src/lib.rs[]
----
====
endif::[]

Run the test with: `cargo test`.

In the output, will see:
----
running 2 tests
test my_test_ok ... ok
test my_test_ko ... FAILED

...

failures:
    my_test_ko

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
----

== Rustlings

To use rustlings with docker:
----
docker run -it -v $(pwd):/project -w /project rust /bin/bash
cd rustlings
cargo install --force --path .
cd /project
rustlings watch
----

== Dissassembly

We can see the assembly code generated with the command:
----
objdump --disassemble=[FUNCTION NAME] -S -C target/debug/hello_cargo -EL -M intel --insn-width=8
----

*FUNCTION_NAME*: The name of the function to show (like: `main`). It could be prefixed by the module (example::main).

[%collapsible]
.Output example
====
----
target/debug/hello_cargo:     file format elf64-x86-64


Disassembly of section .init:

Disassembly of section .plt:

Disassembly of section .plt.got:

Disassembly of section .text:

0000000000008a50 <main>:
    8a50:       50                              push   rax
    8a51:       48 89 f2                        mov    rdx,rsi
    8a54:       48 8d 05 15 5f 04 00            lea    rax,[rip+0x45f15]        # 4e970 <__rustc_debug_gdb_scripts_section__>
    8a5b:       8a 00                           mov    al,BYTE PTR [rax]
    8a5d:       48 63 f7                        movsxd rsi,edi
    8a60:       48 8d 3d b9 ff ff ff            lea    rdi,[rip+0xffffffffffffffb9]        # 8a20 <hello_cargo::main>
    8a67:       31 c9                           xor    ecx,ecx
    8a69:       e8 02 00 00 00                  call   8a70 <std::rt::lang_start>
    8a6e:       59                              pop    rcx
    8a6f:       c3                              ret    

Disassembly of section .fini:
----
====

== References

* https://github.com/rust-lang/rustlings[Rustlings]